### ISSUE TITLE
Users should not be able to compare a life stage to itself

### ISSUE THREAD

**Issue by astrasb** [astrasb/Strongyloides_Bioinformatics#15]
At the Select Life Stage Comparisons, add code that checks to see if the same life stage appears in both the target and contrast groups. If so, throw an (informative) error.

**Comment by sfdemarco** [comment]
I fixed this for the simple case of having the same life stage in both the target and contrast spots, but I'm still trying to figure it out for the multiple comparisons situation.

**Comment by astrasb** [comment]
FYI: when I pushed the big update to v3.0.0 last night, I commented out the partial fix in the primary branch, because of the issue with the fix not allowing users to run comparisons where the number of life stages in the target and contrast groups aren't even - e.g. iL3 vs (FLF+PF). I added a commented note in the flow of the code.

**Comment by sfdemarco** [comment]
Gotcha! Sounds good!

**Comment by astrasb** [comment]
Addressed this with merge #47
